// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hexuywzcuiiyldiwxuvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhleHV5d3pjdWlpeWxkaXd4dXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODg5NDQsImV4cCI6MjA2OTU2NDk0NH0.ivmhZk-yDjazPpWLGbHU2m0hNH_M-AWwYAtFnRJAUD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});